defaults: &defaults
  aplication: Projeto Fractal
  email: contato@projetofractal.com.br
  modules:
    subscribers: false
    categories: true
    clients: true
    testimonials: true
    documents: true
    polls: true
    events: true
    employees: true
    galleries: true
    links: true
    news: true
    pages: true
    products: true
    projects: true
    services: true
    videos: true
  will_paginate:
    per_page: 10

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults